version: '3.9'
name: harpokrates-dev
services:
  frontend:
    container_name: harpokrates-front
    image: harpokrates-front-dev:latest
    entrypoint: tail -f /dev/null
    ports:
      - "3000:3000"
    volumes:
      - ../harpokrates-frontend/:/usr/src/app/
      - /usr/src/app/node_modules
    depends_on:
      - backend

  backend:
    container_name: harpokrates-back
    image: harpokrates-back-dev:latest
    entrypoint: tail -f /dev/null
    ports:
      - "8080:8080"
    volumes:
      - ../harpokrates-backend/:/usr/src/app/
      - /usr/src/app/node_modules
    depends_on:
       - mongodb
    environment:
      - MONGO_URL=mongodb://root:root@mongodb:27017/

  mongodb:
    container_name: harpokrates-mongodb
    image: mongo:latest
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
    volumes:
      - ./mongodb/data-dev/db:/data/db
      - ./mongodb/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d/