version: '3.9'
name: harpokrates
services:
  frontend:
    container_name: harpokrates-front
    image: harpokrates-front:latest
    ports:
      - "3000:3000"
    depends_on:
      - backend

  backend:
    container_name: harpokrates-back
    image: harpokrates-back:latest
    ports:
      - "8080:8080"
    depends_on:
       - mongodb
    environment:
      - PORT=8080
      - HOST=0.0.0.0
      - MONGO_URL=mongodb://harpokrates:harpokrates@mongodb:27017/harpokrates
      - FLICKR_API_KEY=${FLICKR_API_KEY}
      - FLICKR_CALLS_LIMIT=5

  mongodb:
    container_name: harpokrates-mongodb
    image: mongo:latest
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
    volumes:
      - ./mongodb/data/db:/data/db
      - ./mongodb/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d/
