version: '3.9'
name: harpokrates-dev
services:
  frontend:
    container_name: harpokrates-front-dev
    image: harpokrates-front-dev:latest
    ports:
      - "3000:3000"
    depends_on:
      - backend
    volumes:
      - ../harpokrates-frontend/app:/usr/src/app/app/
      - ../harpokrates-frontend/wasm-lib:/usr/src/app/wasm-lib/

  backend:
    container_name: harpokrates-back-dev
    image: harpokrates-back-dev:latest
    ports:
      - "8080:8080"
    depends_on:
       - mongodb
    environment:
      - PORT=8080
      - HOST=0.0.0.0
      - MONGO_URL=mongodb://harpokrates:harpokrates@mongodb:27017/harpokrates-dev
      - FLICKR_API_KEY=${FLICKR_API_KEY}
      - FLICKR_CALLS_LIMIT=5
    volumes:
      - ../harpokrates-backend/src/:/usr/src/app/src/
      - ../harpokrates-backend/test/:/usr/src/app/test/

  mongodb:
    container_name: harpokrates-mongodb-dev
    image: mongo:latest
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
    volumes:
      - ./mongodb/data/db:/data/db
      - ./mongodb/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d/
