version: '3.9'
name: harpokrates
services:
  frontend:
    container_name: harpokrates-front
    image: harpokrates-front:latest
    entrypoint: node server.js
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - HOSTNAME=0.0.0.0 
    depends_on:
      - backend

  backend:
    container_name: harpokrates-back
    image: harpokrates-back:latest
    entrypoint: node src/server.js 
    ports:
      - "8080:8080"
    depends_on:
       - mongodb
    environment:
      - MONGO_URL=mongodb://root:root@mongodb:27017/

  mongodb:
    container_name: harpokrates-mongodb
    image: mongo:latest
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
    volumes:
      - ./mongodb/data/db:/data/db
      - ./mongodb/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d/
